// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ufhwuhzkpfjmzzdxrsbs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVmaHd1aHprcGZqbXp6ZHhyc2JzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4MTMzODgsImV4cCI6MjA2NDM4OTM4OH0.8_PLvJ0lLg-aEQzwPtz2E_iUmvhowxSmdXAmXbGWi0s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);